# Generated by Django 6.0.4 on 2026-04-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('enclosure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enclosures')),
            ],
        ),
    ]
