# Generated by Django 6.0.4 on 2026-04-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='description',
            new_name='health',
        ),
    ]
